const axios = require("axios");
const surah = {
  alfatihah: 1,
  albaqarah: 2,
  aliimran: 3,
  annisa: 4,
  almaidah: 5,
  alanam: 6,
  alaraf: 7,
  alanfal: 8,
  attauba: 9,
  yunus: 10,
  hud: 11,
  yusuf: 12,
  arrad: 13,
  ibrahim: 14,
  alhijr: 15,
  annahl: 16,
  alisra: 17,
  alkahfi: 18,
  maryam: 19,
  taha: 20,
  alanbiya: 21,
  alhajj: 22,
  almuminun: 23,
  annur: 24,
  alfurqan: 25,
  asysyura: 26,
  annaml: 27,
  alqashash: 28,
  alankabut: 29,
  arrum: 30,
  luqman: 31,
  assajdah: 32,
  alahzab: 33,
  saba: 34,
  faathir: 35,
  yasin: 36,
  ashshaffat: 37,
  sad: 38,
  azzumar: 39,
  almumin: 40,
  hamim: 41,
  ashshura: 42,
  azzukhruf: 43,
  addukhan: 44,
  aljathiya: 45,
  alahqaf: 46,
  muhammad: 47,
  alfath: 48,
  alhujurat: 49,
  qaaf: 50,
  azzariyat: 51,
  attur: 52,
  annajm: 53,
  alqamar: 54,
  arrahman: 55,
  alwaaqiah: 56,
  alhadid: 57,
  almujadila: 58,
  alhasyr: 59,
  almumtahana: 60,
  asshaff: 61,
  aljumuah: 62,
  almunafik: 63,
  attagabun: 64,
  attalaq: 65,
  attahrim: 66,
  almulk: 67,
  alqalam: 68,
  alaqqa: 69,
  almaarij: 70,
  nuh: 71,
  aljinn: 72,
  almuzzammil: 73,
  almuddathth: 74,
  alqiyamat: 75,
  addahr: 76,
  almursalat: 77,
  annabaa: 78,
  annaziat: 79,
  abasa: 80,
  attakwir: 81,
  alinfitar: 82,
  almutaffifin: 83,
  alinshiqaq: 84,
  alburuj: 85,
  attariq: 86,
  alala: 87,
  algashiya: 88,
  alfajr: 89,
  albalad: 90,
  asysyams: 91,
  allail: 92,
  addhuha: 93,
  assyarh: 94,
  attin: 95,
  alalaq: 96,
  alqadr: 97,
  albayyinah: 98,
  alzalzalah: 99,
  aladiyat: 100,
  alqariah: 101,
  attakatsur: 102,
  alasr: 103,
  alhumazah: 104,
  alfil: 105,
  alquraish: 106,
  almaun: 107,
  alkautsar: 108,
  alkafirun: 109,
  annasr: 110,
  allahab: 111,
  alikhlas: 112,
  alfalaq: 113,
  annas: 114,
};

const quran = async (arguments) => {
  return new Promise(async (resolve, reject) => {
    try {
      const getAyah = arguments[1];
      const getSurah = surah[arguments[0]] || arguments[0];
      const fetch = await axios.get(`https://api.quran.sutanlab.id/surah/${getSurah}/${getAyah}`);
      const result = fetch.data;
      if (result.code !== 200) resolve(`Tidak ditemukan Surah-ke ${getSurah} ayat-ke ${getAyah}`);
      const data = result.data;
      const text = `${data.surah.name.transliteration.id} [${data.surah.name.translation.id}] [${getSurah}:${getAyah}] - ${data.surah.name.short}\n\n${data.text.arab}\n\n_*Artinya :*_ ${data.translation.id}`;
      resolve(text);
    } catch (error) {
      reject("Error Quran!");
    }
  });
};

module.exports = quran;
